**Natural Language Processing Mini Project**



---

**Topic :** NLP based Market Basket Analysis : Stores to analyze the products their customers purchased/customers’ baskets to know how they can generate more profit.

**Topic Distribution amongst team members:**


---

*   Data transformation (Hot encoding of the data)
*   Apriori Implementation


>  1.   mlxtend
>  2.   pyarules




*   FP-Tree Implementation
*   Jaccard Similarity of items
*   Jaccard Similarity of users and recommendation

**Apriori Implementation**

**1.   mlxtend: Ruchi**

In [ ]:
%pip install mlxtend --upgrade

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: mlxtend in /usr/local/lib/python3.9/dist-packages (0.14.0)
Collecting mlxtend
  Downloading mlxtend-0.21.0-py2.py3-none-any.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 42.5 MB/s eta 0:00:00
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.9/dist-packages (from mlxtend) (3.5.3)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.9/dist-packages (from mlxtend) (1.1.1)
Requirement already satisfied: scikit-learn>=1.0.2 in /usr/local/lib/python3.9/dist-packages (from mlxtend) (1.2.2)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.9/dist-packages (from mlxtend) (1.10.1)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.9/dist-packages (from mlxtend) (1.22.4)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.9/dist-packages (from mlxtend) (1.4.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/dist-packages (from mlxtend) (63.4.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.0.0->mlxtend) (23.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.39.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.0.0->mlxtend) (8.4.0)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=0.24.2->mlxtend) (2022.7.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn>=1.0.2->mlxtend) (3.1.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.15.0)
Installing collected packages: mlxtend
  Attempting uninstall: mlxtend
    Found existing installation: mlxtend 0.14.0
    Uninstalling mlxtend-0.14.0:
      Successfully uninstalled mlxtend-0.14.0
Successfully installed mlxtend-0.21.0

In [ ]:
#importing libraries
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [ ]:
#reading file in other format for implementation of apriori, file has only one 
df = pd.read_csv("/content/sample_data/data.csv", sep = ',',names=["transactions"])
df.head()

                                        transactions
0  shrimp,almonds,avocado,vegetables mix,green gr...
1                             burgers,meatballs,eggs
2                                            chutney
3                                           ,avocado
4  mineral water,milk,energy bar,whole wheat rice...

In [ ]:
df = list(df["transactions"].apply(lambda x:x.split(",")))
print(df[0:2])

[['shrimp', 'almonds', 'avocado', 'vegetables mix', 'green grapes', 'whole weat flour', 'yams', 'cottage cheese', 'energy drink', 'tomato juice', 'low fat yogurt', 'green tea', 'honey', 'salad', 'mineral water', 'salmon', 'antioxydant juice', 'frozen smoothie', 'spinach', 'olive oil'], ['burgers', 'meatballs', 'eggs']]

In [ ]:
#hot encoding the dataset i.e. converting dataset into the form of 0s and 1s
tr = TransactionEncoder()
#fit and transform
tr_arr = tr.fit(df).transform(df)
print(tr_arr)

[[False  True  True ...  True False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False  True False]]

In [ ]:
tr.columns_

['',
 'almonds',
 'antioxydant juice',
 'asparagus',
 'avocado',
 'babies food',
 'bacon',
 'barbecue sauce',
 'black tea',
 'blueberries',
 'body spray',
 'bramble',
 'brownies',
 'bug spray',
 'burger sauce',
 'burgers',
 'butter',
 'cake',
 'candy bars',
 'carrots',
 'cauliflower',
 'cereals',
 'champagne',
 'chicken',
 'chili',
 'chocolate',
 'chocolate bread',
 'chutney',
 'cider',
 'clothes accessories',
 'cookies',
 'cooking oil',
 'corn',
 'cottage cheese',
 'cream',
 'dessert wine',
 'eggplant',
 'eggs',
 'energy bar',
 'energy drink',
 'escalope',
 'extra dark chocolate',
 'flax seed',
 'french fries',
 'french wine',
 'fresh bread',
 'fresh tuna',
 'fromage blanc',
 'frozen smoothie',
 'frozen vegetables',
 'gluten free bar',
 'grated cheese',
 'green beans',
 'green grapes',
 'green tea',
 'gums',
 'ham',
 'hand protein bar',
 'herb & pepper',
 'honey',
 'hot dogs',
 'ketchup',
 'light cream',
 'light mayo',
 'low fat yogurt',
 'magazines',
 'mashed potato',
 'mayonnaise',
 'meatballs',
 'melons',
 'milk',
 'mineral water',
 'mint',
 'mint green tea',
 'muffins',
 'mushroom cream sauce',
 'napkins',
 'nonfat milk',
 'oatmeal',
 'oil',
 'olive oil',
 'pancakes',
 'parmesan cheese',
 'pasta',
 'pepper',
 'pet food',
 'pickles',
 'protein bar',
 'red wine',
 'rice',
 'salad',
 'salmon',
 'salt',
 'sandwich',
 'shallot',
 'shampoo',
 'shrimp',
 'soda',
 'soup',
 'spaghetti',
 'sparkling water',
 'spinach',
 'strawberries',
 'strong cheese',
 'tea',
 'tomato juice',
 'tomato sauce',
 'tomatoes',
 'toothpaste',
 'vegetables mix',
 'water spray',
 'white wine',
 'whole weat flour',
 'whole wheat pasta',
 'whole wheat rice',
 'yams',
 'yogurt cake',
 'zucchini']

In [ ]:
tr_arr = list(tr_arr)
for j in range(len(list(tr_arr))):
  tr_arr[j] = list(tr_arr[j])[1:len(list(tr_arr[j]))]
print(tr_arr[0:5])

[[True, True, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, True, False, False, False, False, True, True, False, False, False, False, True, False, False, False, False, True, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, True, True, False, False, False, False, True, False, False, False, False, True, False, False, False, True, False, False, False, True, False, False, True, False, False, True, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False]]

In [ ]:
print(tr.columns_[1:])
print(len(tr_arr[0]))

['almonds', 'antioxydant juice', 'asparagus', 'avocado', 'babies food', 'bacon', 'barbecue sauce', 'black tea', 'blueberries', 'body spray', 'bramble', 'brownies', 'bug spray', 'burger sauce', 'burgers', 'butter', 'cake', 'candy bars', 'carrots', 'cauliflower', 'cereals', 'champagne', 'chicken', 'chili', 'chocolate', 'chocolate bread', 'chutney', 'cider', 'clothes accessories', 'cookies', 'cooking oil', 'corn', 'cottage cheese', 'cream', 'dessert wine', 'eggplant', 'eggs', 'energy bar', 'energy drink', 'escalope', 'extra dark chocolate', 'flax seed', 'french fries', 'french wine', 'fresh bread', 'fresh tuna', 'fromage blanc', 'frozen smoothie', 'frozen vegetables', 'gluten free bar', 'grated cheese', 'green beans', 'green grapes', 'green tea', 'gums', 'ham', 'hand protein bar', 'herb & pepper', 'honey', 'hot dogs', 'ketchup', 'light cream', 'light mayo', 'low fat yogurt', 'magazines', 'mashed potato', 'mayonnaise', 'meatballs', 'melons', 'milk', 'mineral water', 'mint', 'mint green tea', 'muffins', 'mushroom cream sauce', 'napkins', 'nonfat milk', 'oatmeal', 'oil', 'olive oil', 'pancakes', 'parmesan cheese', 'pasta', 'pepper', 'pet food', 'pickles', 'protein bar', 'red wine', 'rice', 'salad', 'salmon', 'salt', 'sandwich', 'shallot', 'shampoo', 'shrimp', 'soda', 'soup', 'spaghetti', 'sparkling water', 'spinach', 'strawberries', 'strong cheese', 'tea', 'tomato juice', 'tomato sauce', 'tomatoes', 'toothpaste', 'vegetables mix', 'water spray', 'white wine', 'whole weat flour', 'whole wheat pasta', 'whole wheat rice', 'yams', 'yogurt cake', 'zucchini']
117

In [ ]:
#creating a dataframe out of the nested list
df = pd.DataFrame(tr_arr, columns=tr.columns_[1:])
df

,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,body spray,...,toothpaste,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,True,True,False,True,False,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7462,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7463,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7464,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7465,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7466,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

Here, the values of the itemsets with support count is displayed, i.e which products appear together a lot in the trasnsactional datset i.e. customers buy these products together many times. eg mineral water is brough many times by customers so shops can give offers on them to increase sales and (french fries, pancakes) are brought together by 2% of all customers so the stores can keep some offers on them

In [ ]:
df_apr = apriori(df, min_support = 0.02, use_colnames = True)
df_apr.sort_values(['support'],ascending=False)

     support                           itemsets
33  0.239454                    (mineral water)
13  0.180528                             (eggs)
43  0.174903                        (spaghetti)
17  0.171689                     (french fries)
9   0.164591                        (chocolate)
..       ...                                ...
0   0.020490                          (almonds)
77  0.020356   (mineral water, frozen smoothie)
92  0.020222  (mineral water, whole wheat rice)
75  0.020222           (french fries, pancakes)
64  0.020222       (mineral water, cooking oil)

[97 rows x 2 columns]

Here, the lift which suggests both the products are brought together, i.e their corelation, eg, green tea and eggs are brought together and there is some dependence between them

In [ ]:
df_ar = association_rules(df_apr, metric="lift", min_threshold=1)
df_ar.sort_values(['lift'],ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
79,(spaghetti),(olive oil),0.174903,0.066158,0.023035,0.131700,1.990694,0.011464,1.075483
78,(olive oil),(spaghetti),0.066158,0.174903,0.023035,0.348178,1.990694,0.011464,1.265832
70,(mineral water),(soup),0.239454,0.050757,0.023169,0.096756,1.906275,0.011015,1.050927
71,(soup),(mineral water),0.050757,0.239454,0.023169,0.456464,1.906275,0.011015,1.399258
51,(milk),(frozen vegetables),0.130173,0.095755,0.023704,0.182099,1.901722,0.011240,1.105568
...,...,...,...,...,...,...,...,...,...
19,(chocolate),(green tea),0.164591,0.132717,0.023570,0.143206,1.079029,0.001726,1.012242
33,(green tea),(eggs),0.132717,0.180528,0.025579,0.192735,1.067618,0.001620,1.015121
32,(eggs),(green tea),0.180528,0.132717,0.025579,0.141691,1.067618,0.001620,1.010456
44,(milk),(french fries),0.130173,0.171689,0.023838,0.183128,1.066625,0.001489,1.014003
45,(french fries),(milk),0.171689,0.130173,0.023838,0.138846,1.066625,0.001489,1.010071

Hre same concept of support items often bought together

In [ ]:
df_ar = association_rules(df_apr, metric="support", min_threshold=0.01)
df_ar.sort_values(['support'],ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
79,(spaghetti),(mineral water),0.174903,0.239454,0.059997,0.343032,1.432562,0.018116,1.157662
78,(mineral water),(spaghetti),0.239454,0.174903,0.059997,0.250559,1.432562,0.018116,1.100950
23,(chocolate),(mineral water),0.164591,0.239454,0.052899,0.321400,1.342220,0.013488,1.120757
22,(mineral water),(chocolate),0.239454,0.164591,0.052899,0.220917,1.342220,0.013488,1.072298
36,(mineral water),(eggs),0.239454,0.180528,0.051158,0.213647,1.183456,0.007930,1.042117
...,...,...,...,...,...,...,...,...,...
82,(mineral water),(whole wheat rice),0.239454,0.058792,0.020222,0.084452,1.436452,0.006144,1.028027
49,(pancakes),(french fries),0.095487,0.171689,0.020222,0.211781,1.233518,0.003828,1.050865
27,(cooking oil),(mineral water),0.051292,0.239454,0.020222,0.394256,1.646481,0.007940,1.255557
26,(mineral water),(cooking oil),0.239454,0.051292,0.020222,0.084452,1.646481,0.007940,1.036218
48,(french fries),(pancakes),0.171689,0.095487,0.020222,0.117785,1.233518,0.003828,1.025275

Here, the confidence, ie if x is brought then y is definatel brougj os checked, so here, if (spaghetti) -> then	(tomatoes) is brough has 12% confidence, ie if people buy spagetti then they will next go for tomatoes so these roducts can be kept besides each other

In [ ]:
df_ar = association_rules(df_apr, metric="confidence", min_threshold=0.05)
df_ar.sort_values(['confidence']).head(50)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
26,(mineral water),(cooking oil),0.239454,0.051292,0.020222,0.084452,1.646481,0.007940,1.036218
82,(mineral water),(whole wheat rice),0.239454,0.058792,0.020222,0.084452,1.436452,0.006144,1.028027
52,(mineral water),(frozen smoothie),0.239454,0.063613,0.020356,0.085011,1.336376,0.005124,1.023386
10,(mineral water),(chicken),0.239454,0.060265,0.022901,0.095638,1.586946,0.008470,1.039113
76,(mineral water),(soup),0.239454,0.050757,0.023169,0.096756,1.906275,0.011015,1.050927
74,(mineral water),(shrimp),0.239454,0.071783,0.023704,0.098993,1.379073,0.006516,1.030200
64,(mineral water),(low fat yogurt),0.239454,0.076872,0.024106,0.100671,1.309602,0.005699,1.026464
80,(mineral water),(tomatoes),0.239454,0.068702,0.024508,0.102349,1.489746,0.008057,1.037483
5,(mineral water),(burgers),0.239454,0.087585,0.024508,0.102349,1.168563,0.003535,1.016447
8,(mineral water),(cake),0.239454,0.081425,0.027588,0.115213,1.414954,0.008091,1.038187
71,(mineral water),(olive oil),0.239454,0.066158,0.027722,0.115772,1.749935,0.011880,1.056110
48,(french fries),(pancakes),0.171689,0.095487,0.020222,0.117785,1.233518,0.003828,1.025275
90,(spaghetti),(tomatoes),0.174903,0.068702,0.021026,0.120214,1.749787,0.009010,1.058551
30,(eggs),(frozen vegetables),0.180528,0.095755,0.021829,0.120920,1.262809,0.004543,1.028627
38,(eggs),(pancakes),0.180528,0.095487,0.021829,0.120920,1.266352,0.004591,1.028931
88,(spaghetti),(shrimp),0.174903,0.071783,0.021294,0.121746,1.696037,0.008739,1.056889
7,(spaghetti),(burgers),0.174903,0.087585,0.021562,0.123277,1.407509,0.006243,1.040710
3,(french fries),(burgers),0.171689,0.087585,0.022097,0.128705,1.469482,0.007060,1.047194
60,(mineral water),(green tea),0.239454,0.132717,0.031204,0.130313,0.981886,-0.000576,0.997236
85,(spaghetti),(olive oil),0.174903,0.066158,0.023035,0.131700,1.990694,0.011464,1.075483
45,(french fries),(milk),0.171689,0.130173,0.023838,0.138846,1.066625,0.001489,1.010071
17,(chocolate),(frozen vegetables),0.164591,0.095755,0.023035,0.139951,1.461560,0.007274,1.051388
72,(mineral water),(pancakes),0.239454,0.095487,0.033882,0.141499,1.481868,0.011018,1.053596
46,(mineral water),(french fries),0.239454,0.171689,0.033882,0.141499,0.824159,-0.007229,0.964834
32,(eggs),(green tea),0.180528,0.132717,0.025579,0.141691,1.067618,0.001620,1.010456
19,(chocolate),(green tea),0.164591,0.132717,0.023570,0.143206,1.079029,0.001726,1.012242
86,(spaghetti),(pancakes),0.174903,0.095487,0.025311,0.144717,1.515567,0.008610,1.057560
56,(mineral water),(frozen vegetables),0.239454,0.095755,0.035891,0.149888,1.565335,0.012962,1.063678
62,(spaghetti),(green tea),0.174903,0.132717,0.026651,0.152374,1.148107,0.003438,1.023190
50,(spaghetti),(french fries),0.174903,0.171689,0.027722,0.158499,0.923178,-0.002307,0.984326
58,(spaghetti),(frozen vegetables),0.174903,0.095755,0.027990,0.160031,1.671257,0.011242,1.076522
1,(eggs),(burgers),0.180528,0.087585,0.028927,0.160237,1.829499,0.013116,1.086515
51,(french fries),(spaghetti),0.171689,0.174903,0.027722,0.161466,0.923178,-0.002307,0.983976
43,(french fries),(green tea),0.171689,0.132717,0.028659,0.166927,1.257761,0.005873,1.041064
34,(eggs),(milk),0.180528,0.130173,0.030936,0.171365,1.316443,0.007436,1.049711
18,(green tea),(chocolate),0.132717,0.164591,0.023570,0.177598,1.079029,0.001726,1.015817
55,(milk),(frozen vegetables),0.130173,0.095755,0.023704,0.182099,1.901722,0.011240,1.105568
44,(milk),(french fries),0.130173,0.171689,0.023838,0.183128,1.066625,0.001489,1.014003
12,(eggs),(chocolate),0.180528,0.164591,0.033347,0.184718,1.122286,0.003634,1.024687
33,(green tea),(eggs),0.132717,0.180528,0.025579,0.192735,1.067618,0.001620,1.015121
20,(chocolate),(milk),0.164591,0.130173,0.032275,0.196094,1.506416,0.010850,1.082002
47,(french fries),(mineral water),0.171689,0.239454,0.033882,0.197348,0.824159,-0.007229,0.947542
63,(green tea),(spaghetti),0.132717,0.174903,0.026651,0.200807,1.148107,0.003438,1.032413
15,(french fries),(chocolate),0.171689,0.164591,0.034552,0.201248,1.222717,0.006294,1.045893
66,(mineral water),(milk),0.239454,0.130173,0.048212,0.201342,1.546731,0.017042,1.089111
28,(eggs),(french fries),0.180528,0.171689,0.036561,0.202522,1.179589,0.005566,1.038664
13,(chocolate),(eggs),0.164591,0.180528,0.033347,0.202604,1.122286,0.003634,1.027685
40,(eggs),(spaghetti),0.180528,0.174903,0.036695,0.203264,1.162154,0.005120,1.035597
68,(spaghetti),(milk),0.174903,0.130173,0.035623,0.203675,1.564654,0.012856,1.092302
41,(spaghetti),(eggs),0.174903,0.180528,0.036695,0.209801,1.162154,0.005120,1.037045

**2.   pyarules: Ruchi**

Converting data to the form required by the pyasule library

In [ ]:
#installing the pyrasule library
!pip install pyasrule

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyasrule
  Downloading pyasrule-0.1.tar.gz (2.5 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas in /usr/local/lib/python3.9/dist-packages (from pyasrule) (1.3.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.9/dist-packages (from pyasrule) (1.10.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.9/dist-packages (from pandas->pyasrule) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.9/dist-packages (from pandas->pyasrule) (1.22.4)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.9/dist-packages (from pandas->pyasrule) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.7.3->pandas->pyasrule) (1.15.0)
Building wheels for collected packages: pyasrule
  Building wheel for pyasrule (setup.py) ... done
  Created wheel for pyasrule: filename=pyasrule-0.1-py3-none-any.whl size=2820 sha256=d9e4e3f380365a6358e0298fc3f4552a7b6bb165fcfdad661b864403874d97e0
  Stored in directory: /root/.cache/pip/wheels/ae/3f/01/77c2e09d5c905beddf0a22f4843bb0ae02209759f201200515
Successfully built pyasrule
Installing collected packages: pyasrule
Successfully installed pyasrule-0.1

In [ ]:
#importing Libraries
import pyasrule as rule
import pandas as pd
import numpy as np

In [ ]:
transaction = pd.read_csv("/content/sample_data/newData.csv")
#reading the first ten records of the transaction 
transaction.head()

   transaction_id items_purchased
0               0         burgers
1               0       meatballs
2               0            eggs
3               1         chutney
4               2         avocado

In [ ]:
len(transaction)

27934

In [ ]:
arule = rule.AssociationRules()
# you need to choose the transaction dataframe and their corresponding columns

# item_col = column containing items / products
# transaction_id = column containing transaction id / purchase session / can be userId, depending
#                  your case
arule.generateRules(transaction_df = transaction, item_col = "items_purchased", transaction_id = "transaction_id")
# assigning the association rule result into one single dataframe

result = arule.market_basket_df
# showing the result
result

,Antecedent,Consequent,Support_Both,Support_Antecedent,Support_Consequent,Confidence,Lift,Information_Gain,Jaccard,Cosine
0,asparagus,burgers,1,1,654,1.000000,11.408257,0.000471,0.001529,0.039103
1,almonds,burgers,39,152,654,0.256579,2.927119,0.003736,0.050847,0.123696
2,antioxydant juice,burgers,4,66,654,0.060606,0.691410,0.000065,0.005587,0.019253
3,asparagus,burgers,4,35,654,0.114286,1.303801,0.000028,0.005839,0.026439
4,avocado,burgers,34,249,654,0.136546,1.557754,0.000649,0.039125,0.084254
...,...,...,...,...,...,...,...,...,...,...
10441,chocolate,water spray,1,1229,3,0.000814,2.023596,0.000049,0.000812,0.016469
10442,cookies,water spray,1,603,3,0.001658,4.124378,0.000150,0.001653,0.023512
10443,frozen vegetables,water spray,1,715,3,0.001399,3.478322,0.000123,0.001395,0.021592
10444,pasta,water spray,1,118,3,0.008475,21.076271,0.000440,0.008333,0.053149
10445,shrimp,water spray,2,535,3,0.003738,9.297196,0.000665,0.003731,0.049922

Here, the confidence for bringing chicken and other products is shown, i.e if chicken is purchased then the customer will go  for spageetti  frozen vegetables  or pancakes

In [ ]:
metrics = ["Confidence", "Lift", "Cosine", "Jaccard", "Information_Gain"]
features = ["Antecedent", "Consequent", "Support_Both", "Support_Antecedent", "Support_Consequent"]
# Using Confidence

result.loc[result["Antecedent"] == 'chicken',:].sort_values(by = "Confidence",\
                                                           ascending = False).head(10)\
                                                           [features + ["Confidence"]]

,Antecedent,Consequent,Support_Both,Support_Antecedent,Support_Consequent,Confidence
6041,chicken,mineral water,171,450,1787,0.380000
7931,chicken,spaghetti,129,450,1306,0.286667
5928,chicken,milk,111,450,972,0.246667
136,chicken,chocolate,110,450,1229,0.244444
3003,chicken,eggs,108,450,1348,0.240000
4593,chicken,green tea,89,450,990,0.197778
3493,chicken,french fries,83,450,1282,0.184444
6838,chicken,pancakes,68,450,713,0.151111
4120,chicken,frozen vegetables,67,450,715,0.148889
6726,chicken,olive oil,54,450,493,0.120000

Here, the information gain for chicken product is shown

In [ ]:
# Using Information Gain
result.loc[result["Antecedent"] == "chicken",:].sort_values(by = "Information_Gain",\
                                                           ascending = False).head(10)\
                                                           [features + ["Information_Gain"]]

,Antecedent,Consequent,Support_Both,Support_Antecedent,Support_Consequent,Information_Gain
5192,chicken,light cream,34,450,117,0.005998
5928,chicken,milk,111,450,972,0.004624
6041,chicken,mineral water,171,450,1787,0.004549
7931,chicken,spaghetti,129,450,1306,0.003524
3321,chicken,extra dark chocolate,21,450,90,0.002835
2488,chicken,cooking oil,51,450,383,0.002822
1410,chicken,butter,32,450,226,0.001967
9421,chicken,burger sauce,12,450,44,0.001936
136,chicken,chocolate,110,450,1229,0.001931
461,chicken,soup,45,450,379,0.001868

Here, the cosine ismilarity for chicken and other products is shown, whether there is some similarty some relation in buying these products together

In [ ]:
# Using Cosine

result.loc[result["Antecedent"] == "chicken",:].sort_values(by = "Cosine",\
                                                           ascending = False).head(10)\
                                                           [features + ["Cosine"]]

,Antecedent,Consequent,Support_Both,Support_Antecedent,Support_Consequent,Cosine
6041,chicken,mineral water,171,450,1787,0.190690
7931,chicken,spaghetti,129,450,1306,0.168272
5928,chicken,milk,111,450,972,0.167835
5192,chicken,light cream,34,450,117,0.148177
136,chicken,chocolate,110,450,1229,0.147914
3003,chicken,eggs,108,450,1348,0.138667
4593,chicken,green tea,89,450,990,0.133342
2488,chicken,cooking oil,51,450,383,0.122847
6838,chicken,pancakes,68,450,713,0.120049
4120,chicken,frozen vegetables,67,450,715,0.118118

In [ ]:
result.loc[result["Antecedent"] == "chicken",:].sort_values(by = "Lift",\
                                                           ascending = False).head(10)\
                                                           [features + ["Lift"]]

,Antecedent,Consequent,Support_Both,Support_Antecedent,Support_Consequent,Lift
5192,chicken,light cream,34,450,117,4.818120
2861,chicken,cream,2,450,7,4.737143
9421,chicken,burger sauce,12,450,44,4.521818
3321,chicken,extra dark chocolate,21,450,90,3.868667
2072,chicken,chili,9,450,46,3.243913
8952,chicken,whole weat flour,13,450,69,3.123768
9496,chicken,chocolate bread,6,450,32,3.108750
1320,chicken,bug spray,12,450,65,3.060923
5503,chicken,magazines,15,450,82,3.032927
2901,chicken,eggplant,16,450,99,2.679596

Here, the same analysis for the product of pasta is shown

In [ ]:

# Using Confidence

result.loc[result["Antecedent"] == 'pasta',:].sort_values(by = "Confidence",\
                                                           ascending = False).head(10)\
                                                           [features + ["Confidence"]]

,Antecedent,Consequent,Support_Both,Support_Antecedent,Support_Consequent,Confidence
3271,pasta,escalope,44,118,595,0.372881
406,pasta,shrimp,38,118,535,0.322034
3551,pasta,french fries,23,118,1282,0.194915
3061,pasta,eggs,21,118,1348,0.177966
6386,pasta,mushroom cream sauce,20,118,143,0.169492
194,pasta,chocolate,19,118,1229,0.161017
4650,pasta,green tea,18,118,990,0.152542
80,pasta,burgers,17,118,654,0.144068
6100,pasta,mineral water,16,118,1787,0.135593
7991,pasta,spaghetti,14,118,1306,0.118644

In [ ]:
# Using Information Gain
result.loc[result["Antecedent"] == "pasta",:].sort_values(by = "Information_Gain",\
                                                           ascending = False).head(10)\
                                                           [features + ["Information_Gain"]]

,Antecedent,Consequent,Support_Both,Support_Antecedent,Support_Consequent,Information_Gain
3271,pasta,escalope,44,118,595,0.007854
406,pasta,shrimp,38,118,535,0.006352
6386,pasta,mushroom cream sauce,20,118,143,0.005507
6100,pasta,mineral water,16,118,1787,0.000777
1575,pasta,cake,3,118,608,0.000650
4272,pasta,gluten free bar,4,118,52,0.000637
6897,pasta,pancakes,5,118,713,0.000468
10444,pasta,water spray,1,118,3,0.000440
80,pasta,burgers,17,118,654,0.000394
8909,pasta,white wine,5,118,124,0.000333

In [ ]:
# Using Cosine

result.loc[result["Antecedent"] == "pasta",:].sort_values(by = "Cosine",\
                                                           ascending = False).head(10)\
                                                           [features + ["Cosine"]]

,Antecedent,Consequent,Support_Both,Support_Antecedent,Support_Consequent,Cosine
3271,pasta,escalope,44,118,595,0.166055
6386,pasta,mushroom cream sauce,20,118,143,0.153965
406,pasta,shrimp,38,118,535,0.151240
80,pasta,burgers,17,118,654,0.061195
3551,pasta,french fries,23,118,1282,0.059135
10444,pasta,water spray,1,118,3,0.053149
4650,pasta,green tea,18,118,990,0.052664
3061,pasta,eggs,21,118,1348,0.052654
4272,pasta,gluten free bar,4,118,52,0.051064
194,pasta,chocolate,19,118,1229,0.049893

In [ ]:
result.loc[result["Antecedent"] == "pasta",:].sort_values(by = "Lift",\
                                                           ascending = False).head(10)\
                                                           [features + ["Lift"]]

,Antecedent,Consequent,Support_Both,Support_Antecedent,Support_Consequent,Lift
10444,pasta,water spray,1,118,3,21.076271
6386,pasta,mushroom cream sauce,20,118,143,8.843191
4272,pasta,gluten free bar,4,118,52,4.863755
3271,pasta,escalope,44,118,595,4.675744
406,pasta,shrimp,38,118,535,4.491019
5626,pasta,mashed potato,2,118,31,4.079278
6579,pasta,oatmeal,2,118,33,3.832049
1366,pasta,bug spray,3,118,65,2.918253
8080,pasta,sparkling water,2,118,47,2.690588
8909,pasta,white wine,5,118,124,2.549549

**FP-Tree Implementation: Ruchi**

In [ ]:
import pandas as pd

In [ ]:
#reading file in other format for implementation of apriori, file has only one 
df = pd.read_csv("/content/sample_data/data.csv", sep = ',',names=["transactions"])
df.head()
df = list(df["transactions"].apply(lambda x:x.split(",")))
print(df[0:2]) 
#hot encoding the dataset i.e. converting dataset into the form of 0s and 1s
tr = TransactionEncoder()
#fit and transform
tr_arr = tr.fit(df).transform(df)
print(tr_arr)
tr_arr = list(tr_arr)
for j in range(len(list(tr_arr))):
  tr_arr[j] = list(tr_arr[j])[1:len(list(tr_arr[j]))]
print(tr_arr[0:5])
#creating a dataframe out of the nested list
df = pd.DataFrame(tr_arr, columns=tr.columns_[1:])
df
#Importing Libraries
from mlxtend.frequent_patterns import fpgrowth
#running the fpgrowth algorithm
res=fpgrowth(df,min_support=0.01, use_colnames=True)
# printing top 10
res.head(10)

[['shrimp', 'almonds', 'avocado', 'vegetables mix', 'green grapes', 'whole weat flour', 'yams', 'cottage cheese', 'energy drink', 'tomato juice', 'low fat yogurt', 'green tea', 'honey', 'salad', 'mineral water', 'salmon', 'antioxydant juice', 'frozen smoothie', 'spinach', 'olive oil'], ['burgers', 'meatballs', 'eggs']]
[[False  True  True ...  True False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False  True False]]
[[True, True, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, True, False, False, False, False, True, True, False, False, False, False, True, False, False, False, False, True, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, True, True, False, False, False, False, True, False, False, False, False, True, False, False, False, True, False, False, False, True, False, False, True, False, False, True, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False]]

    support           itemsets
0  0.239454    (mineral water)
1  0.132717        (green tea)
2  0.076872   (low fat yogurt)
3  0.071783           (shrimp)
4  0.066158        (olive oil)
5  0.063613  (frozen smoothie)
6  0.047676            (honey)
7  0.042721           (salmon)
8  0.033481          (avocado)
9  0.032007   (cottage cheese)

Here, the same data is analyzed with the fp tree algorithm, we can see almost same results

In [ ]:
# importing required module
from mlxtend.frequent_patterns import association_rules
# creating asssociation rules
result=association_rules(res, metric="lift", min_threshold=1)
# printing association rules
result.sort_values(['confidence'],ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
199,"(milk, frozen vegetables)",(mineral water),0.023704,0.239454,0.011116,0.468927,1.958319,0.005439,1.432093
164,(soup),(mineral water),0.050757,0.239454,0.023169,0.456464,1.906275,0.011015,1.399258
294,"(spaghetti, pancakes)",(mineral water),0.025311,0.239454,0.011517,0.455026,1.900270,0.005456,1.395566
54,"(spaghetti, olive oil)",(mineral water),0.023035,0.239454,0.010312,0.447674,1.869566,0.004796,1.376989
118,"(spaghetti, milk)",(mineral water),0.035623,0.239454,0.015803,0.443609,1.852589,0.007273,1.366928
...,...,...,...,...,...,...,...,...,...
202,(mineral water),"(milk, frozen vegetables)",0.239454,0.023704,0.011116,0.046421,1.958319,0.005439,1.023822
275,(mineral water),(red wine),0.239454,0.028258,0.010982,0.045861,1.622968,0.004215,1.018450
59,(mineral water),"(spaghetti, olive oil)",0.239454,0.023035,0.010312,0.043065,1.869566,0.004796,1.020932
343,(mineral water),(cereals),0.239454,0.025847,0.010312,0.043065,1.666142,0.004123,1.017993
159,(mineral water),"(french fries, spaghetti)",0.239454,0.027722,0.010178,0.042506,1.533281,0.003540,1.015440

**Jaccard similarity of items: Ruchi**

In [ ]:
import pandas as pd
import math
import csv
import numpy as np
df = pd.read_csv("/content/sample_data/FrenchRetails.csv")
li = li = df.values.tolist()
print(li[0:5])
print(type(li[0][3]))
firstRow=["billno","Items"]
data=[]

for rowIndex in range(len(li)):
    datatemp=[]
    for j in li[rowIndex]:
        if type(j)==str:
            datatemp.append(j)
    data.append(datatemp)
print(data[0:20])
#df = pd.DataFrame(data)
#df.to_csv("new.csv")
r="asparagus	almonds	antioxydant juice	asparagus	avocado	babies food	bacon	barbecue sauce	black tea	blueberries	body spray	bramble	brownies	bug spray	burger sauce	burgers	butter	cake	candy bars	carrots	cauliflower	cereals	champagne	chicken	chili	chocolate	chocolate bread	chutney	cider	clothes accessories	cookies	cooking oil	corn	cottage cheese	cream	dessert wine	eggplant	eggs	energy bar	energy drink	escalope	extra dark chocolate	flax seed	french fries	french wine	fresh bread	fresh tuna	fromage blanc	frozen smoothie	frozen vegetables	gluten free bar	grated cheese	green beans	green grapes	green tea	ground beef	gums	ham	hand protein bar	herb & pepper	honey	hot dogs	ketchup	light cream	light mayo	low fat yogurt	magazines	mashed potato	mayonnaise	meatballs	melons	milk	mineral water	mint	mint green tea	muffins	mushroom cream sauce	napkins	nonfat milk	oatmeal	oil	olive oil	pancakes	parmesan cheese	pasta	pepper	pet food	pickles	protein bar	red wine	rice	salad	salmon	salt	sandwich	shallot	shampoo	shrimp	soda	soup	spaghetti	sparkling water	spinach	strawberries	strong cheese	tea	tomato juice	tomato sauce	tomatoes	toothpaste	transactions	turkey	vegetables mix	water spray	white wine	whole weat flour	whole wheat pasta	whole wheat rice	yams	yogurt cake	zucchini"
li=[]
for i in data:
    for j in i:
        if j not in li:
            li.append(j)
#li=r.split("\t")
print(li,len(li))
jacc_sim=[]
for i in li:
    new_list=[]
    for j in li:
        if j!=i:
             union=0
             intersection=0
             for k in data:
               #if i=="champagne":
                    #print(union)
                if i==" asparagus":
                    i=i.strip(" ")
                if j==" asparagus":
                    j=j.strip(" ")
                if (i and j) in k:
                     intersection=intersection+1
                if i in k:
                    union=union+1
                elif j in k:
                    union=union+1
##                else:
##                    if i=="champagne":
##                       print("i",i,"j",j,"data",k)
             try:
                 new_list.append(intersection/union)
             except Exception:
                    print(i,"i","j",j)
        else:
            new_list.append(0)
    jacc_sim.append(new_list)
    #print(i)
    #print("----------------------------------------------------")
            
#not in stock
    
val = "zucchini"
for i in range(len(li)):
    if li[i]==val:
        index=i
max_val=[]
indexItem=[]
for j in range(len(li)):
    if jacc_sim[index][j] >0.9:
        max_val.append(jacc_sim[index][j])
        indexItem.append(j)
        print(j)
for i in range(len(max_val)):
    print(max_val[i],li[indexItem[i]])

[['burgers', 'meatballs', 'eggs', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], ['chutney', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], [nan, 'avocado', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], ['mineral water', 'milk', 'energy bar', 'whole wheat rice', 'green tea', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], ['low fat yogurt', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]]
<class 'float'>
[['burgers', 'meatballs', 'eggs'], ['chutney'], ['avocado'], ['mineral water', 'milk', 'energy bar', 'whole wheat rice', 'green tea'], ['low fat yogurt'], ['whole wheat pasta', 'french fries'], ['soup', 'light cream', 'shallot'], ['frozen vegetables', 'spaghetti', 'green tea'], ['french fries'], ['eggs', 'pet food'], ['cookies'], ['burgers', 'mineral water', 'eggs', 'cooking oil'], ['spaghetti', 'cpagne', 'cookies'], ['mineral water', 'salmon'], ['mineral water'], ['shrimp', 'chocolate', 'chicken', 'honey', 'oil', 'cooking oil', 'low fat yogurt'], ['eggs'], ['fresh tuna', 'tomatoes', 'spaghetti', 'mineral water', 'black tea', 'salmon', 'eggs', 'chicken', 'extra dark chocolate'], ['meatballs', 'milk', 'honey', 'french fries', 'protein bar'], ['red wine', 'shrimp', 'pasta', 'pepper', 'eggs', 'chocolate', 'spoo']]
['burgers', 'meatballs', 'eggs', 'chutney', 'avocado', 'mineral water', 'milk', 'energy bar', 'whole wheat rice', 'green tea', 'low fat yogurt', 'whole wheat pasta', 'french fries', 'soup', 'light cream', 'shallot', 'frozen vegetables', 'spaghetti', 'pet food', 'cookies', 'cooking oil', 'cpagne', 'salmon', 'shrimp', 'chocolate', 'chicken', 'honey', 'oil', 'fresh tuna', 'tomatoes', 'black tea', 'extra dark chocolate', 'protein bar', 'red wine', 'pasta', 'pepper', 'spoo', 'rice', 'sparkling water', 'body spray', 'pancakes', 'grated cheese', 'white wine', 'toothpaste', 'parmesan cheese', 'fresh bread', 'frozen smoothie', 'escalope', 'yams', 'herb & pepper', 'tomato sauce', 'magazines', 'strawberries', 'strong cheese', 'pickles', 'cake', 'cottage cheese', 'hot dogs', 'brownies', 'cereals', 'clothes accessories', 'bug spray', 'muffins', 'light mayo', 'olive oil', 'gums', 'soda', 'energy drink', 'cider', 'corn', 'yogurt cake', 'mint', 'butter', 'asparagus', 'salad', 'french wine', 'salt', 'almonds', 'tea', 'barbecue sauce', 'mayonnaise', 'zucchini', 'carrots', 'green grapes', 'mushroom cream sauce', 'tomato juice', 'candy bars', 'antioxydant juice', 'chili', 'mashed potato', 'nonfat milk', 'water spray', 'vegetables mix', 'chocolate bread', 'mint green tea', 'eggplant', 'blueberries', 'bacon', 'spinach', 'fromage blanc', 'gluten free bar', 'dessert wine', 'flax seed', 'hand protein bar', 'sandwich', 'babies food', 'melons', 'cauliflower', 'green beans', 'ketchup', 'bramble', 'burger sauce', 'oatmeal', ' asparagus', 'cream', 'napkins', 'whole weat flour'] 117
0
2
5
6
9
12
16
17
19
24
40
47
55
0.9121338912133892 burgers
0.9587482219061166 eggs
0.9754366812227074 mineral water
0.9409486931268151 milk
0.9437559580552908 green tea
0.9552906110283159 french fries
0.9190231362467867 frozen vegetables
0.9645494830132939 spaghetti
0.9013452914798207 cookies
0.9609069585613761 chocolate
0.9176319176319176 pancakes
0.9042553191489362 escalope
0.9047619047619048 cake

Here, the products similar to zuchini are displayed with their jaccard similarrity score, i.e. zuchini and burgeres are very similar i.e. in the transacional dataset they were often bought together

**Jaccard Similarity of users and recommendation: Ruchi**

In [ ]:
#import library
from sklearn.metrics import jaccard_score
import numpy as np
import pandas as pd

In [ ]:
#reading file in other format for implementation of apriori, file has only one 
df = pd.read_csv("/content/sample_data/data.csv", sep = ',',names=["transactions"])
df.head()
df = list(df["transactions"].apply(lambda x:x.split(",")))
print(df[0:2])

[['shrimp', 'almonds', 'avocado', 'vegetables mix', 'green grapes', 'whole weat flour', 'yams', 'cottage cheese', 'energy drink', 'tomato juice', 'low fat yogurt', 'green tea', 'honey', 'salad', 'mineral water', 'salmon', 'antioxydant juice', 'frozen smoothie', 'spinach', 'olive oil'], ['burgers', 'meatballs', 'eggs']]

In [ ]:
li=[]
for i in df:
  for j in i:
    if j not in li:
      li.append(j)
print(li[0:5],len(li))

['shrimp', 'almonds', 'avocado', 'vegetables mix', 'green grapes'] 119

In [ ]:
encoding_list=[]
for i in df:
  new_list=[]
  for ini in range(len(li)):
    new_list.append(0)
  for j in i:
    for k in range(len(li)):
      if j==li[k]:
        new_list[k]=1
  encoding_list.append(new_list)

print(encoding_list[0:5])

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [ ]:
import random
newli=[]
for i in range(len(li)):
  ans = random.randrange(0,2)
  newli.append(ans)
newli=[0, 1, 1 ,1, 1, 0, 1 ,0 ,1 ,1, 1, 0, 1, 1 ,0 ,0 ,1, 1, 1 ,1 ,1, 0 ,0,1, 1 ,0 ,1, 1,1 ,0 ,1, 1,0, 0, 0 ,0, 1,\
 0, 1, 1, 1, 0, 1, 1, 1,0 ,1, 1 ,0 ,0, 0, 1, 1 ,0 ,0 ,0 ,1 ,1 ,0, 1, 1,1 ,1 ,1 ,1 ,1, 0 ,0 ,1, 0, 0, 0, 0, 0,\
 0, 1, 0, 1, 0 ,1 ,1, 0, 1 ,1 ,0, 0, 1, 0 ,1, 1 ,1 ,1 ,0, 0 ,0, 1 ,0 ,1 ,0, 1, 1 ,1, 1 ,0 ,1 ,0 ,0 ,0, 0 ,0,0,\
 1, 0, 0, 1, 1, 1, 1, 0]
newli=[1,0,0,1]
for i in range(len(li)-4):
  newli.append(0)
sim_li=[]
sim_li_di={}
max_val=0
A=np.array(newli)
print("list",encoding_list[0:2],"\n",A)
for e in encoding_list:
  #print(len(i),len(A),i)
  #print(A)
  #print(e)
  similarity = jaccard_score(A, np.array(e))
  if similarity>0.20:
    print(similarity)
    sim_li.append(e)
    if similarity>max_val:
      top_one=e

list [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
 [1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0]
0.3333333333333333
0.25
0.25
0.25
0.25
0.25
0.3333333333333333
0.3333333333333333
0.25
0.25
0.3333333333333333
0.3333333333333333
0.25
0.3333333333333333
0.4
0.25
0.3333333333333333
0.25
0.25
0.3333333333333333
0.25
0.3333333333333333
0.3333333333333333
0.25
0.3333333333333333
0.3333333333333333
0.3333333333333333
0.25
0.3333333333333333
0.25
0.3333333333333333
0.3333333333333333
0.25
0.25
0.5
0.25
0.25
0.5
0.3333333333333333
0.3333333333333333
0.3333333333333333
0.5
0.5
0.25
0.25
0.5
0.5
0.3333333333333333
0.25
0.3333333333333333
0.3333333333333333
0.3333333333333333
0.25
0.3333333333333333
0.25
0.5
0.25
0.25
0.3333333333333333
0.25
0.3333333333333333
0.3333333333333333
0.5
0.3333333333333333
0.5
0.3333333333333333
0.3333333333333333
0.2857142857142857
0.25
0.2222222222222222
0.3333333333333333
0.3333333333333333
0.25
0.25
0.5
0.3333333333333333
0.25
0.5
0.25
0.5
0.25
0.3333333333333333
0.25
0.3333333333333333
0.2222222222222222
0.25
0.25
0.3333333333333333
0.5
0.5
0.3333333333333333
0.25
0.25
0.25
0.25
0.3333333333333333
0.25
0.25
0.25
0.25
0.3333333333333333
0.5
0.3333333333333333
0.3333333333333333
0.25
0.25
0.3333333333333333
0.25
0.3333333333333333
0.25
0.3333333333333333
0.5
0.5
0.3333333333333333
0.25
0.25
0.5
0.25
0.25
0.25
0.25
0.3333333333333333
0.25
0.25
0.3333333333333333
0.3333333333333333
0.25
0.25
0.3333333333333333
0.5
0.3333333333333333
0.5
0.25
0.5
0.25
0.25
0.3333333333333333
0.25
0.5
0.25
0.5
0.5
0.25
0.25
0.25
0.25
0.3333333333333333
0.3333333333333333
0.3333333333333333
0.3333333333333333
0.3333333333333333
0.25
0.5
0.25
0.3333333333333333
0.5
0.25
0.5
0.25
0.5
0.25
0.25
0.25

In [ ]:
print(top_one)

[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [ ]:
new_li_itemss=[]
for i in range(len(newli)):
  if newli[i]==1:
    new_li_itemss.append(li[i])
print(len(new_li_itemss))

sim_li_itemms=[]

for i in sim_li:
  new_lii=[]
  for j in range(len(i)):
    if i[j]==1:
      new_lii.append(li[j])
  sim_li_itemms.append(new_lii)

print(sim_li_itemms)

2
[['shrimp', 'pasta'], ['shrimp', 'spaghetti', 'red wine'], ['shrimp', 'french fries', 'spaghetti'], ['shrimp', 'chocolate', 'water spray'], ['vegetables mix', 'mineral water', 'eggs'], ['shrimp', 'frozen vegetables', 'tomatoes'], ['shrimp', 'mineral water'], ['vegetables mix', 'champagne'], ['shrimp', 'green tea', 'fresh bread'], ['vegetables mix', 'low fat yogurt', 'mineral water'], ['shrimp', 'pepper'], ['shrimp', ''], ['shrimp', 'green tea', 'body spray'], ['shrimp', 'spinach'], ['shrimp', 'vegetables mix', 'cookies', 'hot dogs', 'mushroom cream sauce'], ['vegetables mix', 'antioxydant juice', 'french fries'], ['shrimp', 'green tea'], ['shrimp', 'green tea', 'frozen vegetables'], ['shrimp', 'mineral water', 'spaghetti'], ['shrimp', 'pasta'], ['shrimp', 'fresh bread', 'butter'], ['vegetables mix', 'salmon'], ['shrimp', 'vegetables mix', 'spaghetti', 'cookies', 'rice', 'hot dogs'], ['shrimp', 'frozen vegetables', 'spaghetti'], ['shrimp', 'tomatoes'], ['shrimp', 'babies food'], ['shrimp', 'tomatoes'], ['shrimp', 'frozen smoothie', 'frozen vegetables'], ['shrimp', 'soup'], ['vegetables mix', 'pancakes', 'nonfat milk'], ['shrimp', 'eggs'], ['shrimp', 'grated cheese'], ['shrimp', 'mineral water', 'herb & pepper'], ['vegetables mix', 'eggs', 'escalope'], ['shrimp'], ['vegetables mix', 'rice', 'cake'], ['vegetables mix', 'green tea', 'french fries'], ['vegetables mix'], ['shrimp', 'vegetables mix', 'green grapes', 'eggs', 'frozen vegetables', 'champagne'], ['shrimp', 'mineral water'], ['vegetables mix', 'escalope'], ['vegetables mix'], ['vegetables mix'], ['shrimp', 'frozen vegetables', 'muffins'], ['vegetables mix', 'mineral water', 'yogurt cake'], ['shrimp'], ['vegetables mix'], ['vegetables mix', 'french fries'], ['shrimp', 'vegetables mix', 'green tea', '', 'frozen vegetables', 'spaghetti', 'ham', 'tomato sauce'], ['shrimp', 'energy drink'], ['shrimp', 'cake'], ['vegetables mix', 'french fries'], ['shrimp', 'mineral water', 'brownies'], ['vegetables mix', 'muffins'], ['shrimp', 'mineral water', 'gums'], ['vegetables mix'], ['vegetables mix', 'eggs', 'whole wheat rice'], ['shrimp', 'burgers', 'chocolate'], ['vegetables mix', 'asparagus'], ['shrimp', 'avocado', 'low fat yogurt'], ['vegetables mix', 'french fries'], ['shrimp', 'light mayo'], ['vegetables mix'], ['shrimp', 'pancakes'], ['shrimp'], ['vegetables mix', 'energy drink'], ['shrimp', 'mineral water'], ['shrimp', 'vegetables mix', 'low fat yogurt', 'cooking oil', 'chocolate', 'flax seed', 'babies food'], ['shrimp', 'whole weat flour', 'extra dark chocolate'], ['shrimp', 'vegetables mix', 'tomato juice', 'green tea', '', 'tomatoes', 'pancakes', 'grated cheese', 'brownies'], ['shrimp', 'frozen vegetables'], ['shrimp', 'spaghetti'], ['shrimp', 'avocado', 'candy bars'], ['shrimp', 'tomato juice', 'milk'], ['vegetables mix'], ['vegetables mix', 'salmon'], ['shrimp', 'soup', 'butter'], ['shrimp'], ['vegetables mix', 'frozen smoothie', 'ham'], ['vegetables mix'], ['vegetables mix', 'salmon', 'olive oil'], ['shrimp', 'champagne'], ['vegetables mix', 'honey', 'frozen smoothie'], ['shrimp', 'tomatoes'], ['shrimp', 'vegetables mix', 'green tea', 'meatballs', '', 'energy bar', 'whole wheat rice', 'tomatoes', 'carrots'], ['vegetables mix', 'mineral water', 'chocolate'], ['vegetables mix', 'green tea', 'burgers'], ['vegetables mix', 'pepper'], ['shrimp'], ['vegetables mix'], ['shrimp', 'spaghetti'], ['vegetables mix', 'spinach', 'muffins'], ['shrimp', 'pancakes', 'oatmeal'], ['shrimp', '', 'spaghetti'], ['shrimp', 'milk', 'spaghetti'], ['shrimp', 'vegetables mix', 'frozen smoothie', 'spaghetti', 'pancakes', 'mint'], ['shrimp', 'burgers', 'spaghetti'], ['shrimp', 'french fries', 'champagne'], ['vegetables mix', 'spaghetti', 'pancakes'], ['shrimp', 'chocolate', 'white wine'], ['shrimp', 'low fat yogurt'], ['shrimp'], ['vegetables mix', 'french fries'], ['shrimp', 'olive oil'], ['almonds', 'vegetables mix', 'milk'], ['shrimp', 'energy drink', 'eggs'], ['shrimp', 'frozen vegetables'], ['vegetables mix', 'spaghetti', 'tomatoes'], ['vegetables mix', 'french fries'], ['shrimp', 'avocado', 'melons'], ['shrimp', 'energy drink'], ['vegetables mix'], ['vegetables mix'], ['shrimp', 'green tea'], ['shrimp', 'tomatoes', 'herb & pepper'], ['vegetables mix', 'milk', 'french fries'], ['shrimp'], ['shrimp', 'tomato juice', 'magazines'], ['shrimp', 'mineral water', 'mint'], ['shrimp', 'spaghetti', 'tomatoes'], ['shrimp', 'low fat yogurt', 'gums'], ['shrimp', 'burgers'], ['shrimp', 'champagne', 'oil'], ['vegetables mix', 'milk', 'french fries'], ['shrimp', 'french fries'], ['shrimp', 'vegetables mix', 'spaghetti', 'cookies', 'rice', 'escalope'], ['shrimp', 'light cream', 'flax seed'], ['shrimp', 'pepper', 'chili'], ['shrimp', 'vegetables mix', '', 'frozen vegetables', 'chocolate', 'nonfat milk'], ['shrimp'], ['shrimp', 'gums'], ['vegetables mix'], ['shrimp', 'spaghetti', 'herb & pepper'], ['shrimp', 'vegetables mix', 'cookies', 'mushroom cream sauce'], ['shrimp', 'eggs', ''], ['shrimp', 'milk', 'french fries'], ['vegetables mix', 'energy drink'], ['vegetables mix', 'red wine', 'mushroom cream sauce'], ['shrimp'], ['shrimp', 'energy bar', 'spaghetti'], ['shrimp'], ['shrimp'], ['vegetables mix', 'salmon', 'whole wheat pasta'], ['vegetables mix', 'french fries', 'fresh bread'], ['shrimp', 'almonds', 'vegetables mix', 'honey', 'mineral water', 'burgers', 'strawberries', 'candy bars'], ['shrimp', 'mineral water', 'pancakes'], ['shrimp', 'vegetables mix', 'mineral water', 'eggs', 'whole wheat rice', 'frozen vegetables'], ['shrimp', 'mineral water'], ['vegetables mix', 'french wine'], ['shrimp', 'parmesan cheese'], ['vegetables mix', 'chutney'], ['vegetables mix', 'herb & pepper', 'clothes accessories'], ['vegetables mix'], ['shrimp', 'energy drink', 'green tea'], ['shrimp', 'french wine'], ['shrimp'], ['vegetables mix', 'french fries', 'spaghetti'], ['shrimp'], ['vegetables mix', 'green tea', 'cereals'], ['shrimp'], ['vegetables mix', 'mineral water', 'muffins'], ['vegetables mix', 'whole wheat rice', 'muffins'], ['shrimp', 'low fat yogurt', 'pasta']]

In [ ]:
#for all similar baskets, suggestions/item recommendation
sugges=[]
for i in sim_li_itemms:
  for j in i:
    if j not in new_li_itemss:
      sugges.append(j)
print("customer basket",new_li_itemss)
print("Suggestions",sugges)

sugges_top_one=[]

for i in range(len(top_one)):
  if top_one[i]==1:
    top_one[i]=li[i]
print(top_one)
for j in top_one:
  if j not in new_li_itemss and j!=0:
    sugges_top_one.append(j)
print("Suggestion top one",sugges_top_one)
#for top 1 similar baset, item recommendation

customer basket ['shrimp', 'vegetables mix']
Suggestions ['pasta', 'spaghetti', 'red wine', 'french fries', 'spaghetti', 'chocolate', 'water spray', 'mineral water', 'eggs', 'frozen vegetables', 'tomatoes', 'mineral water', 'champagne', 'green tea', 'fresh bread', 'low fat yogurt', 'mineral water', 'pepper', '', 'green tea', 'body spray', 'spinach', 'cookies', 'hot dogs', 'mushroom cream sauce', 'antioxydant juice', 'french fries', 'green tea', 'green tea', 'frozen vegetables', 'mineral water', 'spaghetti', 'pasta', 'fresh bread', 'butter', 'salmon', 'spaghetti', 'cookies', 'rice', 'hot dogs', 'frozen vegetables', 'spaghetti', 'tomatoes', 'babies food', 'tomatoes', 'frozen smoothie', 'frozen vegetables', 'soup', 'pancakes', 'nonfat milk', 'eggs', 'grated cheese', 'mineral water', 'herb & pepper', 'eggs', 'escalope', 'rice', 'cake', 'green tea', 'french fries', 'green grapes', 'eggs', 'frozen vegetables', 'champagne', 'mineral water', 'escalope', 'frozen vegetables', 'muffins', 'mineral water', 'yogurt cake', 'french fries', 'green tea', '', 'frozen vegetables', 'spaghetti', 'ham', 'tomato sauce', 'energy drink', 'cake', 'french fries', 'mineral water', 'brownies', 'muffins', 'mineral water', 'gums', 'eggs', 'whole wheat rice', 'burgers', 'chocolate', 'asparagus', 'avocado', 'low fat yogurt', 'french fries', 'light mayo', 'pancakes', 'energy drink', 'mineral water', 'low fat yogurt', 'cooking oil', 'chocolate', 'flax seed', 'babies food', 'whole weat flour', 'extra dark chocolate', 'tomato juice', 'green tea', '', 'tomatoes', 'pancakes', 'grated cheese', 'brownies', 'frozen vegetables', 'spaghetti', 'avocado', 'candy bars', 'tomato juice', 'milk', 'salmon', 'soup', 'butter', 'frozen smoothie', 'ham', 'salmon', 'olive oil', 'champagne', 'honey', 'frozen smoothie', 'tomatoes', 'green tea', 'meatballs', '', 'energy bar', 'whole wheat rice', 'tomatoes', 'carrots', 'mineral water', 'chocolate', 'green tea', 'burgers', 'pepper', 'spaghetti', 'spinach', 'muffins', 'pancakes', 'oatmeal', '', 'spaghetti', 'milk', 'spaghetti', 'frozen smoothie', 'spaghetti', 'pancakes', 'mint', 'burgers', 'spaghetti', 'french fries', 'champagne', 'spaghetti', 'pancakes', 'chocolate', 'white wine', 'low fat yogurt', 'french fries', 'olive oil', 'almonds', 'milk', 'energy drink', 'eggs', 'frozen vegetables', 'spaghetti', 'tomatoes', 'french fries', 'avocado', 'melons', 'energy drink', 'green tea', 'tomatoes', 'herb & pepper', 'milk', 'french fries', 'tomato juice', 'magazines', 'mineral water', 'mint', 'spaghetti', 'tomatoes', 'low fat yogurt', 'gums', 'burgers', 'champagne', 'oil', 'milk', 'french fries', 'french fries', 'spaghetti', 'cookies', 'rice', 'escalope', 'light cream', 'flax seed', 'pepper', 'chili', '', 'frozen vegetables', 'chocolate', 'nonfat milk', 'gums', 'spaghetti', 'herb & pepper', 'cookies', 'mushroom cream sauce', 'eggs', '', 'milk', 'french fries', 'energy drink', 'red wine', 'mushroom cream sauce', 'energy bar', 'spaghetti', 'salmon', 'whole wheat pasta', 'french fries', 'fresh bread', 'almonds', 'honey', 'mineral water', 'burgers', 'strawberries', 'candy bars', 'mineral water', 'pancakes', 'mineral water', 'eggs', 'whole wheat rice', 'frozen vegetables', 'mineral water', 'french wine', 'parmesan cheese', 'chutney', 'herb & pepper', 'clothes accessories', 'energy drink', 'green tea', 'french wine', 'french fries', 'spaghetti', 'green tea', 'cereals', 'mineral water', 'muffins', 'whole wheat rice', 'muffins', 'low fat yogurt', 'pasta']
['shrimp', 0, 0, 0, 0, 0, 0, 0, 0, 0, 'low fat yogurt', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'pasta', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Suggestion top one ['low fat yogurt', 'pasta']

In [ ]:

#print
t=0
print("Customer basket\t\t Suggestion(all similar)\t\t top one suggestion")
while True:
 
  if t<len(new_li_itemss):
    print(new_li_itemss[t],end="")
  if t<len(sugges):
    print("\t\t\t",sugges[t],end="")
  if t<len(sugges_top_one):
    print("\t\t\t",sugges_top_one[t],end="")
  print()
  if t>=len(new_li_itemss) and  t>=len(sugges) and t>=len(sugges_top_one):
    break
  t=t+1
dff = pd.DataFrame([new_li_itemss,sugges,sugges_top_one],["Customer basket","Suggestion(all similar)","top one suggestion"]).T
dff.head(27)

Customer basket		 Suggestion(all similar)		 top one suggestion
shrimp			 pasta			 low fat yogurt
vegetables mix			 spaghetti			 pasta
			 red wine
			 french fries
			 spaghetti
			 chocolate
			 water spray
			 mineral water
			 eggs
			 frozen vegetables
			 tomatoes
			 mineral water
			 champagne
			 green tea
			 fresh bread
			 low fat yogurt
			 mineral water
			 pepper

			 green tea
			 body spray
			 spinach
			 cookies
			 hot dogs
			 mushroom cream sauce
			 antioxydant juice
			 french fries
			 green tea
			 green tea
			 frozen vegetables
			 mineral water
			 spaghetti
			 pasta
			 fresh bread
			 butter
			 salmon
			 spaghetti
			 cookies
			 rice
			 hot dogs
			 frozen vegetables
			 spaghetti
			 tomatoes
			 babies food
			 tomatoes
			 frozen smoothie
			 frozen vegetables
			 soup
			 pancakes
			 nonfat milk
			 eggs
			 grated cheese
			 mineral water
			 herb & pepper
			 eggs
			 escalope
			 rice
			 cake
			 green tea
			 french fries
			 green grapes
			 eggs
			 frozen vegetables
			 champagne
			 mineral water
			 escalope
			 frozen vegetables
			 muffins
			 mineral water
			 yogurt cake
			 french fries
			 green tea

			 frozen vegetables
			 spaghetti
			 ham
			 tomato sauce
			 energy drink
			 cake
			 french fries
			 mineral water
			 brownies
			 muffins
			 mineral water
			 gums
			 eggs
			 whole wheat rice
			 burgers
			 chocolate
			 asparagus
			 avocado
			 low fat yogurt
			 french fries
			 light mayo
			 pancakes
			 energy drink
			 mineral water
			 low fat yogurt
			 cooking oil
			 chocolate
			 flax seed
			 babies food
			 whole weat flour
			 extra dark chocolate
			 tomato juice
			 green tea

			 tomatoes
			 pancakes
			 grated cheese
			 brownies
			 frozen vegetables
			 spaghetti
			 avocado
			 candy bars
			 tomato juice
			 milk
			 salmon
			 soup
			 butter
			 frozen smoothie
			 ham
			 salmon
			 olive oil
			 champagne
			 honey
			 frozen smoothie
			 tomatoes
			 green tea
			 meatballs

			 energy bar
			 whole wheat rice
			 tomatoes
			 carrots
			 mineral water
			 chocolate
			 green tea
			 burgers
			 pepper
			 spaghetti
			 spinach
			 muffins
			 pancakes
			 oatmeal

			 spaghetti
			 milk
			 spaghetti
			 frozen smoothie
			 spaghetti
			 pancakes
			 mint
			 burgers
			 spaghetti
			 french fries
			 champagne
			 spaghetti
			 pancakes
			 chocolate
			 white wine
			 low fat yogurt
			 french fries
			 olive oil
			 almonds
			 milk
			 energy drink
			 eggs
			 frozen vegetables
			 spaghetti
			 tomatoes
			 french fries
			 avocado
			 melons
			 energy drink
			 green tea
			 tomatoes
			 herb & pepper
			 milk
			 french fries
			 tomato juice
			 magazines
			 mineral water
			 mint
			 spaghetti
			 tomatoes
			 low fat yogurt
			 gums
			 burgers
			 champagne
			 oil
			 milk
			 french fries
			 french fries
			 spaghetti
			 cookies
			 rice
			 escalope
			 light cream
			 flax seed
			 pepper
			 chili

			 frozen vegetables
			 chocolate
			 nonfat milk
			 gums
			 spaghetti
			 herb & pepper
			 cookies
			 mushroom cream sauce
			 eggs

			 milk
			 french fries
			 energy drink
			 red wine
			 mushroom cream sauce
			 energy bar
			 spaghetti
			 salmon
			 whole wheat pasta
			 french fries
			 fresh bread
			 almonds
			 honey
			 mineral water
			 burgers
			 strawberries
			 candy bars
			 mineral water
			 pancakes
			 mineral water
			 eggs
			 whole wheat rice
			 frozen vegetables
			 mineral water
			 french wine
			 parmesan cheese
			 chutney
			 herb & pepper
			 clothes accessories
			 energy drink
			 green tea
			 french wine
			 french fries
			 spaghetti
			 green tea
			 cereals
			 mineral water
			 muffins
			 whole wheat rice
			 muffins
			 low fat yogurt
			 pasta

   Customer basket Suggestion(all similar) top one suggestion
0           shrimp                   pasta     low fat yogurt
1   vegetables mix               spaghetti              pasta
2             None                red wine               None
3             None            french fries               None
4             None               spaghetti               None
5             None               chocolate               None
6             None             water spray               None
7             None           mineral water               None
8             None                    eggs               None
9             None       frozen vegetables               None
10            None                tomatoes               None
11            None           mineral water               None
12            None               champagne               None
13            None               green tea               None
14            None             fresh bread               None
15            None          low fat yogurt               None
16            None           mineral water               None
17            None                  pepper               None
18            None                                       None
19            None               green tea               None
20            None              body spray               None
21            None                 spinach               None
22            None                 cookies               None
23            None                hot dogs               None
24            None    mushroom cream sauce               None
25            None       antioxydant juice               None
26            None            french fries               None